name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: install deps linux
      run: sudo apt install meson pkg-config libfmt-dev python3-dev cython3 python3-pytest
    - name: configure
      run: meson build
    - name: build
      run: ninja -vC build -j2
    - name: pybuild
      run: |
        cd python
        python3 setup.py build_ext --inplace --library-dirs=../build --rpath=`pwd`/../build
    - name: test
      run: |
        meson test -C build --no-rebuild --print-errorlogs -v
        cd python
        python3 -m pytest --log-level=DEBUG -v

# vim: sts=2 sw=2 et
